version: "3.8"
services:
  postgres:
    container_name: kuchi-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: kuchi-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    restart: always  

  nestjs-app:
    build:
      context: .
    container_name: kuchi-backend
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=docker
      - DATABASE_NAME=kuchi-db
    volumes:
      - .:/app
    command: |
      bash -c "
      until nc -z -v -w30 postgres 5432; do
        echo 'Esperando PostgreSQL...';
        sleep 1;
      done;
      echo 'PostgreSQL está pronto!';
      pnpm prisma migrate deploy && pnpm run start:prod"
    restart: always 
