version: "3"
services:
  postgres:
    container_name: kuchi-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: kuchi-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  nestjs-app:
    build: 
      context: .  # Usando o Dockerfile para a construção
    container_name: kuchi-backend
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=docker
      - DATABASE_NAME=nume-api
    volumes:
      - .:/app
    command: |
      bash -c "pnpm prisma migrate dev && pnpm run start:prod"  # Rodar a migração antes de iniciar o app
    restart: always
