version: "3.8"

services:
  postgres:
    container_name: kuchi-db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: kuchi-db
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
    restart: always  
    networks:
      - app-network

  nestjs-app:
    build:
      context: .  # Direcionando para o diretório atual para construir a imagem
    container_name: kuchi-backend
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres  # Nome do serviço do PostgreSQL no Docker
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=docker
      - DATABASE_NAME=kuchi-db
    volumes:
      - .:/app  # Mapear o código-fonte local para dentro do contêiner
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
